<?php
/**
 * Dashboard Main Controller
 * This file serves as the entry point for the dashboard and implements MVC architecture
 */

// Initialize session if not already started
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Check if user is logged in, if not redirect to login page
if (!isset($_SESSION['user'])) {
    header('Location: ../Login/login.php');
    exit;
}

// Get user data from session
$userName = $_SESSION['user']['name'] ?? '';
$userType = $_SESSION['user']['user_type'] ?? 'freelancer'; // Default to freelancer if not set
$user = $_SESSION['user'] ?? [];

// Get theme preference from cookies or system preference
$savedTheme = isset($_COOKIE['theme']) ? $_COOKIE['theme'] : null;
$systemTheme = isset($_SERVER['HTTP_SEC_CH_PREFERS_COLOR_SCHEME']) ? $_SERVER['HTTP_SEC_CH_PREFERS_COLOR_SCHEME'] : null;
$initialTheme = $savedTheme ?: ($systemTheme ?: 'light');

// Include database connection
require_once __DIR__ . '/../../config/database.php';

// Include controllers
require_once __DIR__ . '/controllers/DashboardController.php';
require_once __DIR__ . '/controllers/UserController.php';
require_once __DIR__ . '/controllers/SupportController.php';
require_once __DIR__ . '/controllers/ProjectController.php';

// Initialize controllers
$dashboardController = new DashboardController();
$userController = new UserController();
$supportController = new SupportController();
$projectController = new ProjectController();

// Handle page routing
$page = isset($_GET['page']) ? $_GET['page'] : 'dashboard';

// Process form submissions first
$formResult = [];

// Handle AJAX requests
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    // Handle AJAX requests for support tickets
    if ($page === 'support-tickets') {
        $supportController = new SupportController();
        
        if ($_POST['action'] === 'update_status') {
            // Handle status update via AJAX
            $supportController->updateTicketStatus();
            exit; // Stop execution after AJAX response
        } 
        else if ($_POST['action'] === 'delete_ticket') {
            // Handle ticket deletion via AJAX
            $supportController->ajaxDeleteTicket();
            exit; // Stop execution after AJAX response
        }
    }
    
    // Handle AJAX requests for projects
    if ($page === 'projects') {
        if ($_POST['action'] === 'update_status') {
            // Handle project status update via AJAX
            $projectController->updateProjectStatus();
            exit; // Stop execution after AJAX response
        }
        else if ($_POST['action'] === 'delete_project') {
            // Handle project deletion via AJAX
            $projectController->ajaxDeleteProject();
            exit; // Stop execution after AJAX response
        }
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($page) {
        case 'profile':
            $formResult = $userController->updateProfile();
            break;
        case 'settings':
            if (isset($_POST['change_password'])) {
                $formResult = $userController->updatePassword();
            } elseif (isset($_POST['update_notifications'])) {
                $formResult = $userController->updateNotifications();
            } elseif (isset($_POST['update_privacy'])) {
                $formResult = $userController->updatePrivacy();
            }
            break;
        case 'support-tickets':
            if (isset($_POST['create_ticket'])) {
                $supportController->createTicket();
            } elseif (isset($_POST['update_ticket'])) {
                $supportController->updateTicket();
            }
            break;
    }
}

// Start output buffering to capture the page content
ob_start();

// Route to the appropriate controller/action based on the page parameter
switch ($page) {
    case 'dashboard':
        $dashboardController->index();
        break;
    case 'profile':
        $userController->profile();
        break;
    case 'settings':
        $userController->settings();
        break;
    case 'projects':
        $projectController->userProjects();
        break;
    case 'support-tickets':
        $action = isset($_GET['action']) ? $_GET['action'] : 'list';
        
        switch($action) {
            case 'create':
                $supportController->createTicketForm();
                break;
            case 'view':
                $supportController->viewTicket();
                break;
            case 'admin':
                $supportController->adminTickets();
                break;
            default:
                $supportController->userTickets();
                break;
        }
        break;
    default:
        // Default to dashboard if page not found
        $dashboardController->index();
        break;
}

// Get the content generated by the controller action
$pageContent = ob_get_clean();

// Make sure $content is also defined for any view that might use it instead
$content = $pageContent;

// Now include the layout template which will use $pageContent
include_once __DIR__ . '/views/layout.php';
?>
